app = "chromadb-flyio"
primary_region = "sin"

[build]
image = "chromadb/chroma:1.0.15"

[env]
CHROMA_SERVER_HOST = "::"
CHROMA_SERVER_HTTP_PORT = "8000"
IS_PERSISTENT = "TRUE"
PERSIST_DIRECTORY = "/data"

[[mounts]]
destination = "/data"
source = "chromadb_data"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"