# pnpm-workspace.yaml
packages:
 - 'packages/*'

overrides:
 rollup: 'npm:@rollup/wasm-node'
 tsx: 4.20.6

onlyBuiltDependencies:
 - '@parcel/watcher'
 - browser-tabs-lock
 - esbuild
 - onnxruntime-node
 - protobufjs
 - puppeteer
 - sharp
