// server.ts (at the project root)
import path from 'node:path';
import fs from 'node:fs/promises'; // Use promises for async file reading
import { fileURLToPath } from 'node:url';
import express, { type Request, type Response, type NextFunction } from 'express';
import compression from 'compression'; // Add compression middleware

import { createServer as createViteServer, type ViteDevServer } from 'vite';
import characterRoutes from '#root/src/server/route/character.routes.ts';
import chatRoutes from './src/server/route/chat.routes.ts';
import sirv from 'sirv';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const isProduction = process.env.NODE_ENV === 'production';
const PORT = process.env.PORT || 3000;
const BASE = process.env.BASE || '/'; // Base path for the app

// --- Helper Function to Resolve Project Root ---
const resolve = (p: string) => path.resolve(__dirname, p);

// --- Template HTML paths ---
const templateHtmlDev = resolve('index.html'); // Root index.html for development
const templateHtmlProd = resolve('dist/client/index.html'); // Built index.html for production
const ssrManifestProd = resolve('dist/client/ssr-manifest.json'); // Optional: for production preload hints

async function createServer() {
	const app = express();

	// --- Core Middleware ---
	app.use(compression()); // Apply gzip compression
	app.use(express.json()); // Parse JSON request bodies

	// --- Vite Development Server Middleware (Development ONLY) ---
	let vite: ViteDevServer | undefined;
	if (!isProduction) {
		vite = await createViteServer({
			server: { middlewareMode: true }, // Run Vite in middleware mode
			appType: 'custom', // We'll handle Vite's HTML transforms manually
			base: BASE,
			root: __dirname, // Set project root directory
		});
		// Use Vite's connect instance as middleware. This handles HMR & plugin transforms.
		app.use(vite.middlewares);
		console.log('Vite development server middleware attached.');
	} else {
		// --- Production Static Asset Serving ---
		// Serve files from the 'dist/client' folder generated by `vite build`
		console.log(`Serving static files from ${resolve('dist/client')}`);
		app.use(
			BASE, // Mount at the base path
			sirv(resolve('dist/client'), {
				// Use sirv for efficient static serving
				dev: !isProduction, // Disable dev-specific logs in production
				immutable: true, // Assume files in dist/client are immutable for strong caching
				maxAge: 31536000, // Cache for 1 year
				// etag: true,           // Enable ETag generation if needed
			})
		);
	}

	// --- API Routes ---
	// Mount the imported modular routers under the '/api' prefix using singular nouns
	console.log('Mounting API routes...');
	app.use(`${BASE}api/character`, characterRoutes); // Mount character routes at /api/character
	app.use(`${BASE}api/chat`, chatRoutes); // Mount chat routes at /api/chat

	// --- SSR Catch-all Handler ---
	// This handles all GET requests not previously handled by static serving or API routes.
	app.get('*', async (req: Request, res: Response, next: NextFunction) => {
		// Simple check to skip SSR for API routes
		if (req.originalUrl.startsWith(`${BASE}api/`)) {
			return next(); // Pass request to the next handler (likely 404)
		}

		// Optional: Skip known static file extensions that might be missed by sirv/Vite middleware
		const fileExtension = path.extname(req.originalUrl);
		if (
			[
				'.js',
				'.css',
				'.json',
				'.ico',
				'.png',
				'.jpg',
				'.jpeg',
				'.gif',
				'.svg',
				'.woff',
				'.woff2',
				'.map',
				'.webmanifest',
				'.txt',
				'.xml',
			].includes(fileExtension)
		) {
			// Let static middleware handle or eventually 404
			// console.log(`Skipping SSR for potential static file: ${req.originalUrl}`);
			return next();
		}

		console.log(`Attempting SSR for: ${req.originalUrl}`);
		const url = req.originalUrl;

		try {
			let template: string;
			let render: (
				url: string,
				ssrManifest?: Record<string, string[]>
			) => Promise<{ html: string; head: string }>; // Type for the render function from entry-server
			let ssrManifest: Record<string, string[]> | undefined = undefined;

			if (!isProduction && vite) {
				// == DEVELOPMENT ==
				template = await fs.readFile(templateHtmlDev, 'utf-8'); // Read base HTML template
				template = await vite.transformIndexHtml(url, template); // Apply Vite transforms (injects HMR client, etc.)
				const serverEntry = await vite.ssrLoadModule('/src/entry-server.tsx'); // Load server entry via Vite for HMR
				render = serverEntry.render; // Get the render function
			} else {
				// == PRODUCTION ==
				template = await fs.readFile(templateHtmlProd, 'utf-8'); // Read built HTML template
				const serverEntryPath = resolve('dist/server/entry-server.js'); // Path to built server entry
				const serverEntry = await import(serverEntryPath); // Import the built server module
				render = serverEntry.render; // Get the render function
				// Load SSR manifest in production for potential preload links
				try {
					ssrManifest = JSON.parse(await fs.readFile(ssrManifestProd, 'utf-8'));
				} catch (manifestError) {
					console.warn(
						`SSR Manifest not found or invalid at ${ssrManifestProd}. Preload links disabled.`
					);
					ssrManifest = undefined; // Continue without manifest if it fails
				}
			}

			// --- Render the React application to HTML ---
			// The render function in entry-server.tsx should handle React rendering (renderToString or renderToPipeableStream)
			// and potentially data fetching, Emotion style extraction, etc.
			const { html: appHtml, head: headContent } = await render(url, ssrManifest);

			// --- Inject rendered content into the HTML template ---
			const finalHtml = template
				.replace(`<!--ssr-outlet-->`, appHtml) // Inject main app HTML
				.replace(`<!--head-outlet-->`, headContent || ''); // Inject head elements (styles, meta tags)

			// --- Send the final HTML response ---
			res.status(200).set({ 'Content-Type': 'text/html' }).end(finalHtml);
		} catch (e: any) {
			// If an error occurs during SSR, let Vite fix the stack trace (dev only)
			if (vite) {
				vite.ssrFixStacktrace(e);
			}
			console.error(`SSR Error processing ${req.originalUrl}:`, e.stack || e);
			next(e); // Pass the error to the default Express error handler
		}
	});

	// --- Default Express Error Handler ---
	// This catches errors passed via next(e)
	app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
		console.error('Unhandled Error Caught:', err.stack || err);
		// Avoid sending detailed stack trace in production
		const statusCode = (err as any).statusCode || 500; // Use status code from error if available
		const message = isProduction ? 'Internal Server Error' : err.message || 'Something went wrong';
		res.status(statusCode).json({ error: message }); // Send JSON error response
		// OR send a simple text/HTML response: res.status(statusCode).send(message);
	});

	// --- Start HTTP Server ---
	app.listen(PORT, () => {
		console.log(`Server started successfully.`);
		console.log(`Mode: ${isProduction ? 'Production' : 'Development'}`);
		console.log(`Listening on: http://localhost:${PORT}${BASE}`);
	});
}

// --- Initialize Server ---
createServer().catch((err) => {
	console.error('Fatal error during server startup:', err);
	process.exit(1); // Exit if server fails to start
});
