// src/shared/config/langConstants.ts

export type LangCode = 'kor' | 'eng';
export const DEFAULT_LANG: LangCode = 'kor';
type LanguageMap = Record<LangCode, string>;

// The outer record now uses this dynamic LanguageMap type.

export const LANG_KEYS = {
	STATIC_SESSION_DISABLE: 'STATIC_SESSION_DISABLE',
	STATIC_SENDING_DISABLE: 'STATIC_SENDING_DISABLE',
	SESSIONS_WITH_CHARACTER: 'SESSIONS_WITH_CHARACTER',
	CREATE_NEW_PROFILE: 'CREATE_NEW_PROFILE',
	START_NEW_SESSION: 'START_NEW_SESSION',
	ADULT_SESSION: 'ADULT_SESSION',
	GENERAL_SESSION: 'GENERAL_SESSION',
	USER_TITLE: 'USER_TITLE',
	CHOOSE_EXISTING_PROFILE: 'CHOOSE_EXISTING_PROFILE',
	CREATE_PROFILE: 'CREATE_PROFILE',
	EDIT_PROFILE: 'EDIT_PROFILE',
	ENTER_DATE: 'ENTER_DATE',
	CREATE_DATE: 'CREATE_DATE',
	UPDATE_DATE: 'UPDATE_DATE',
	GENDER: 'GENDER',
	MALE: 'MALE',
	FEMALE: 'FEMALE',
	OTHER: 'OTHER',
	ERROR: 'ERROR',
	LAST: 'LAST',
	CHARACTERS: 'CHARACTERS',
	USER_INFO: 'USER_INFO',
	EDIT_USER_INFO: 'EDIT_USER_INFO',
	MY_CHARACTERS: 'MY_CHARACTERS',
	MY_SESSIONS: 'MY_SESSIONS',
	USER_NOTE: 'USER_NOTE',
	LOGOUT: 'LOGOUT',
	EDIT: 'EDIT',
	SAVE: 'SAVE',
	SAVE_ANYWAY: 'SAVE_ANYWAY',
	SEND: 'SEND',
	STOP_GENERATION: 'STOP_GENERATION',
	STORY: 'STORY',
	CANCEL: 'CANCEL',
	MORE: 'MORE',
	STATISTICS: 'STATISTICS',
	LOADING_CHARACTERS: 'LOADING_CHARACTERS',
	LOADING_CHAT: 'LOADING_CHAT',
	LOADING_SESSIONS: 'LOADING_SESSIONS',
	LOADING_STORIES: 'LOADING_STORIES',
	LOADING_STORY: 'LOADING_STORY',
	LOADING_USER: 'LOADING_USER',
	FAILED_LOAD_CHAT: 'FAILED_LOAD_CHAT',
	CREATING_SESSION: 'CREATING_SESSION',
	GEN_RESPONSE: 'GEN_RESPONSE',
	NEW_CHARACTER: 'NEW_CHARACTER',
	EDIT_CHARACTER: 'EDIT_CHARACTER',
	CHARACTER_CREATED_SUCCESS: 'CHARACTER_CREATED_SUCCESS',
	CHARACTER_UPDATED_SUCCESS: 'CHARACTER_UPDATED_SUCCESS',
	NO_IMAGES: 'NO_IMAGES',
	PORTRAIT: 'PORTRAIT',
	EMOTION: 'EMOTION',
	BASIC_INFO: 'BASIC_INFO',
	CREATING: 'CREATING',
	CREATE: 'CREATE',
	UPDATE: 'UPDATE',
	UPDATING: 'UPDATING',
	NAME: 'NAME',
	SHOWNAME: 'SHOWNAME',
	DESCRIPTION: 'DESCRIPTION',
	WORLD_INTRODUCTION: 'WORLD_INTRODUCTION',
	EMAIL: 'EMAIL',
	CONTACT: 'CONTACT',
	NOCOMMENT: 'NOCOMMENT',
	INSTRUCTION: 'INSTRUCTION',
	TITLE: 'TITLE',
	SESSION_TITLE: 'SESSION_TITLE',
	SELECT_IMAGE: 'SELECT_IMAGE',
	CHARACTER_DETAIL: 'CHARACTER_DETAIL',
	TITLE_GUIDANCE: 'TITLE_GUIDANCE',
	FIRST_MESSAGE: 'FIRST_MESSAGE',
	NEW_CHARACTER_TITLE: 'NEW_CHARACTER_TITLE',
	NO_SESSIONS: 'NO_SESSIONS',
	NO_PROFILES: 'NO_PROFILES',
	NO_HISTORIES: 'NO_HISTORIES',
	ERROR_MAXLENGTH: 'ERROR_MAXLENGTH',
	SAVE_SUCCESS: 'SAVE_SUCCESS',
	API_KEYS: 'API_KEYS',
	API_KEYS_DESCRIPTION: 'API_KEYS_DESCRIPTION',
	SAVE_API_KEYS: 'SAVE_API_KEYS',
	SAVING: 'SAVING',
	MODIFIED: 'MODIFIED',
	VALIDATING: 'VALIDATING',
	API_KEYS_SAVED_SUCCESS: 'API_KEYS_SAVED_SUCCESS',
	API_KEYS_SAVE_FAILED: 'API_KEYS_SAVE_FAILED',
	LORE_SAVED_SUCCESS: 'LORE_SAVED_SUCCESS',
	HISTORY_SAVED_SUCCESS: 'HISTORY_SAVED_SUCCESS',

	// --- [NEW] Emotion Keys ---
	NEUTRAL: 'NEUTRAL',
	HAPPY: 'HAPPY',
	ANGRY: 'ANGRY',
	SAD: 'SAD',
	FEAR: 'FEAR',
	CURIOUS: 'CURIOUS',
	AFFECTIONATE: 'AFFECTIONATE',
	EXCITED: 'EXCITED',
	DISGUSTED: 'DISGUSTED',
	CONFIDENT: 'CONFIDENT',
	ASHAMED: 'ASHAMED',
	AMAZED: 'AMAZED',
	BORED: 'BORED',
	ROMANTIC: 'ROMANTIC',
	CONFLICTED: 'CONFLICTED',

	INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
	FILE_TOO_LARGE: 'FILE_TOO_LARGE',
	IMAGE_UPLOADED_FOR: 'IMAGE_UPLOADED_FOR',
	FAILED_TO_CREATE_CHARACTER: 'FAILED_TO_CREATE_CHARACTER',
	ERROR_CREATING_CHARACTER: 'ERROR_CREATING_CHARACTER',
	SHOW_NAME_REQUIRED: 'SHOW_NAME_REQUIRED',
	NAME_REQUIRED: 'NAME_REQUIRED',
	GENDER_REQUIRED: 'GENDER_REQUIRED',
	TITLE_REQUIRED: 'TITLE_REQUIRED',
	DESCRIPTION_REQUIRED: 'DESCRIPTION_REQUIRED',
	WORLD_INTRODUCTION_REQUIRED: 'WORLD_INTRODUCTION_REQUIRED',
	INSTRUCTION_REQUIRED: 'INSTRUCTION_REQUIRED',
	WORLD_LORE_REQUIRED: 'WORLD_LORE_REQUIRED',
	FIRST_MESSAGE_REQUIRED: 'FIRST_MESSAGE_REQUIRED',
	SHOW_NAME_PLACEHOLDER: 'SHOW_NAME_PLACEHOLDER',
	NAME_PLACEHOLDER: 'NAME_PLACEHOLDER',
	CONTACT_PLACEHOLDER: 'CONTACT_PLACEHOLDER',
	TITLE_PLACEHOLDER: 'TITLE_PLACEHOLDER',
	DESCRIPTION_PLACEHOLDER: 'DESCRIPTION_PLACEHOLDER',
	WORLD_INTRODUCTION_PLACEHOLDER: 'WORLD_INTRODUCTION_PLACEHOLDER',
	INSTRUCTION_PLACEHOLDER: 'INSTRUCTION_PLACEHOLDER',
	FIRST_MESSAGE_PLACEHOLDER: 'FIRST_MESSAGE_PLACEHOLDER',
	USER_NOTE_PLACEHOLDER: 'USER_NOTE_PLACEHOLDER',
	DESCRIPTION_HELPER: 'DESCRIPTION_HELPER',
	WORLD_INTRODUCTION_HELPER: 'WORLD_INTRODUCTION_HELPER',
	INSTRUCTION_HELPER: 'INSTRUCTION_HELPER',
	FIRST_MESSAGE_HELPER: 'FIRST_MESSAGE_HELPER',

	API_KEY_VALIDATION_RESULTS: 'API_KEY_VALIDATION_RESULTS',
	API_KEYS_VALIDATION_WARNING: 'API_KEYS_VALIDATION_WARNING',
	API_KEY_IS_VALID: 'API_KEY_IS_VALID',
	API_KEY_IS_INVALID: 'API_KEY_IS_INVALID',
	VALIDATION_FAILED_NETWORK_ERROR: 'VALIDATION_FAILED_NETWORK_ERROR',
	FAILED_TO_VALIDATE_API_KEYS: 'FAILED_TO_VALIDATE_API_KEYS',
	MESSAGE_PLACEHOLDER: 'MESSAGE_PLACEHOLDER',
	SESSION_SETTINGS: 'SESSION_SETTINGS',
	CHAT_DISPLAY_MODE: 'CHAT_DISPLAY_MODE',
	BOOK_MODE: 'BOOK_MODE',
	CONVERSATION_MODE: 'CONVERSATION_MODE',
	CHAT_FONT_SIZE: 'CHAT_FONT_SIZE',
	SMALL_FONT: 'SMALL_FONT',
	MEDIUM_FONT: 'MEDIUM_FONT',
	LARGE_FONT: 'LARGE_FONT',
	NORMAL_FONT: 'NORMAL_FONT',
	BOLD_FONT: 'BOLD_FONT',
	DECREASE_FONT_SIZE: 'DECREASE_FONT_SIZE',
	INCREASE_FONT_SIZE: 'INCREASE_FONT_SIZE',
	SESSION_DOCUMENTS: 'SESSION_DOCUMENTS',
	BACK_TO_CONVERSATION: 'BACK_TO_CONVERSATION',
	NEW_DOCUMENT: 'NEW_DOCUMENT',
	DOCUMENT_GENERATION_REQUEST: 'DOCUMENT_GENERATION_REQUEST',
	DOCUMENT_REWRITE_INSTRUCTION: 'DOCUMENT_REWRITE_INSTRUCTION',
	LAST_DOCUMENT_REQUEST: 'LAST_DOCUMENT_REQUEST',
	DOCUMENT_COMPARISON: 'DOCUMENT_COMPARISON',
	SHOW_DOCUMENT_COMPARISON: 'SHOW_DOCUMENT_COMPARISON',
	HIDE_DOCUMENT_COMPARISON: 'HIDE_DOCUMENT_COMPARISON',
	DOCUMENT_FILTER_ALL: 'DOCUMENT_FILTER_ALL',
	DOCUMENT_FILTER_INCLUDED: 'DOCUMENT_FILTER_INCLUDED',
	DOCUMENT_FILTER_NOT_INCLUDED: 'DOCUMENT_FILTER_NOT_INCLUDED',
	NO_FILTERED_DOCUMENTS: 'NO_FILTERED_DOCUMENTS',
	AI_DOCUMENT_GENERATION_IN_PROGRESS: 'AI_DOCUMENT_GENERATION_IN_PROGRESS',
	USE_IN_CONVERSATION_RAG: 'USE_IN_CONVERSATION_RAG',
	GENERATE_DOCUMENT: 'GENERATE_DOCUMENT',
	REWRITE_DOCUMENT: 'REWRITE_DOCUMENT',
	LOADING_DOCUMENTS: 'LOADING_DOCUMENTS',
	NO_DOCUMENTS: 'NO_DOCUMENTS',
	SELECT_OR_CREATE_DOCUMENT: 'SELECT_OR_CREATE_DOCUMENT',
	UNKNOWN_DOCUMENT_ISSUER: 'UNKNOWN_DOCUMENT_ISSUER',
	DOCUMENT_ORIGIN_MANUAL: 'DOCUMENT_ORIGIN_MANUAL',
	DOCUMENT_ORIGIN_AI: 'DOCUMENT_ORIGIN_AI',
	DOCUMENT_TITLE: 'DOCUMENT_TITLE',
	DOCUMENT_KIND: 'DOCUMENT_KIND',
	DOCUMENT_ISSUER: 'DOCUMENT_ISSUER',
	DOCUMENT_VIEWPOINT: 'DOCUMENT_VIEWPOINT',
	DOCUMENT_CLAIM_MODE: 'DOCUMENT_CLAIM_MODE',
	DOCUMENT_EVENT_KEY: 'DOCUMENT_EVENT_KEY',
	DOCUMENT_TIMELINE_ORDER: 'DOCUMENT_TIMELINE_ORDER',
	DOCUMENT_IN_WORLD_TIME: 'DOCUMENT_IN_WORLD_TIME',
	DOCUMENT_CLAIM_RECORD: 'DOCUMENT_CLAIM_RECORD',
	DOCUMENT_CLAIM_STATEMENT: 'DOCUMENT_CLAIM_STATEMENT',
	DOCUMENT_CLAIM_REPORT: 'DOCUMENT_CLAIM_REPORT',
	DOCUMENT_CLAIM_RUMOR: 'DOCUMENT_CLAIM_RUMOR',
	DOCUMENT_CLAIM_OPINION: 'DOCUMENT_CLAIM_OPINION',
	DOCUMENT_CLAIM_PROPAGANDA: 'DOCUMENT_CLAIM_PROPAGANDA',
	DOCUMENT_CLAIM_UNKNOWN: 'DOCUMENT_CLAIM_UNKNOWN',
	DOCUMENT_CONTENT: 'DOCUMENT_CONTENT',
	DOCUMENT_STATUS_DRAFT: 'DOCUMENT_STATUS_DRAFT',
	DOCUMENT_STATUS_APPROVED: 'DOCUMENT_STATUS_APPROVED',
	DOCUMENT_STATUS_ARCHIVED: 'DOCUMENT_STATUS_ARCHIVED',
	DELETE: 'DELETE',
	APPROVE: 'APPROVE',
	ARCHIVE: 'ARCHIVE',
	CONFIRM_APPROVE_DOCUMENT: 'CONFIRM_APPROVE_DOCUMENT',
	CONFIRM_DELETE_DOCUMENT: 'CONFIRM_DELETE_DOCUMENT',
	VIEW_CHARACTER_IMAGE: 'VIEW_CHARACTER_IMAGE',
	AVATAR_MISSING: 'AVATAR_MISSING',
	SAVE_CHANGES: 'SAVE_CHANGES',
	PROFILE_CARD_TABS: 'PROFILE_CARD_TABS',
	ERROR_OCCURRED: 'ERROR_OCCURRED',
	AI_MODELS: 'AI_MODELS',
	NONE: 'NONE',
	PROVIDER: 'PROVIDER',
	SHOW_API_KEY: 'SHOW_API_KEY',
	CANCEL_EDIT: 'CANCEL_EDIT',
	PREVIOUS_RESPONSE: 'PREVIOUS_RESPONSE',
	NEXT_RESPONSE: 'NEXT_RESPONSE',
	EDIT_THIS_TURN: 'EDIT_THIS_TURN',
	REGENERATE_RESPONSE: 'REGENERATE_RESPONSE',
	AI_MODEL: 'AI_MODEL',
} as const;
export type LangKey = keyof typeof LANG_KEYS;

export type LangRecord = Record<LangKey[number], LanguageMap>;
export const langConstants: LangRecord = {
	MESSAGE_PLACEHOLDER: { kor: '메시지를 입력하세요', eng: 'Enter your message' },
	SESSION_SETTINGS: { kor: '세션 설정', eng: 'Session settings' },
	CHAT_DISPLAY_MODE: { kor: '대화 표시 방식', eng: 'Chat display mode' },
	BOOK_MODE: { kor: '북 모드', eng: 'Book mode' },
	CONVERSATION_MODE: { kor: '대화 모드', eng: 'Conversation mode' },
	CHAT_FONT_SIZE: { kor: '대화 글자 크기', eng: 'Chat font size' },
	SMALL_FONT: { kor: '작게', eng: 'Small' },
	MEDIUM_FONT: { kor: '보통', eng: 'Medium' },
	LARGE_FONT: { kor: '크게', eng: 'Large' },
	NORMAL_FONT: { kor: '보통 굵기', eng: 'Normal weight' },
	BOLD_FONT: { kor: '굵게', eng: 'Bold' },
	DECREASE_FONT_SIZE: { kor: '글자 작게', eng: 'Decrease font size' },
	INCREASE_FONT_SIZE: { kor: '글자 크게', eng: 'Increase font size' },
	SESSION_DOCUMENTS: { kor: '세션 문서', eng: 'Documents' },
	BACK_TO_CONVERSATION: { kor: '대화로 돌아가기', eng: 'Back to conversation' },
	NEW_DOCUMENT: { kor: '새 문서', eng: 'New Document' },
	DOCUMENT_GENERATION_REQUEST: {
		kor: '만들 문서를 자연어로 요청',
		eng: 'Describe the document to create',
	},
	DOCUMENT_REWRITE_INSTRUCTION: {
		kor: '현재 초안을 어떻게 고칠지 요청',
		eng: 'Describe how to edit this draft',
	},
	LAST_DOCUMENT_REQUEST: { kor: '최근 AI 요청', eng: 'Last AI request' },
	DOCUMENT_COMPARISON: { kor: '이전 초안과 비교', eng: 'Compare with previous draft' },
	SHOW_DOCUMENT_COMPARISON: { kor: '비교 보기', eng: 'Show comparison' },
	HIDE_DOCUMENT_COMPARISON: { kor: '비교 숨기기', eng: 'Hide comparison' },
	DOCUMENT_FILTER_ALL: { kor: '전체', eng: 'All' },
	DOCUMENT_FILTER_INCLUDED: { kor: '세계관', eng: 'Lore' },
	DOCUMENT_FILTER_NOT_INCLUDED: { kor: '기타', eng: 'Other' },
	NO_FILTERED_DOCUMENTS: { kor: '조건에 맞는 문서가 없습니다.', eng: 'No matching documents.' },
	AI_DOCUMENT_GENERATION_IN_PROGRESS: {
		kor: '문서를 작성하고 있습니다...',
		eng: 'Generating the document...',
	},
	USE_IN_CONVERSATION_RAG: { kor: '세계관에 추가하기', eng: 'Add to world lore' },
	GENERATE_DOCUMENT: { kor: '생성', eng: 'Generate' },
	REWRITE_DOCUMENT: { kor: 'AI로 고치기', eng: 'Rewrite with AI' },
	LOADING_DOCUMENTS: { kor: '문서를 불러오는 중입니다...', eng: 'Loading documents...' },
	NO_DOCUMENTS: { kor: '저장된 문서가 없습니다.', eng: 'No saved documents.' },
	SELECT_OR_CREATE_DOCUMENT: {
		kor: '문서를 선택하거나 새 문서를 만드세요.',
		eng: 'Select a document or create a new one.',
	},
	UNKNOWN_DOCUMENT_ISSUER: { kor: '발행 주체 미정', eng: 'Unknown issuer' },
	DOCUMENT_ORIGIN_MANUAL: { kor: '직접 작성', eng: 'Manual' },
	DOCUMENT_ORIGIN_AI: { kor: 'AI 생성', eng: 'AI generated' },
	DOCUMENT_TITLE: { kor: '제목', eng: 'Title' },
	DOCUMENT_KIND: { kor: '문서 유형', eng: 'Document type' },
	DOCUMENT_ISSUER: { kor: '발행 주체', eng: 'Issuer' },
	DOCUMENT_VIEWPOINT: { kor: '관점', eng: 'Viewpoint' },
	DOCUMENT_CLAIM_MODE: { kor: '주장 성격', eng: 'Claim mode' },
	DOCUMENT_EVENT_KEY: { kor: '사건 식별자', eng: 'Event identity' },
	DOCUMENT_TIMELINE_ORDER: { kor: '세계 내 시간 순서', eng: 'In-world timeline order' },
	DOCUMENT_IN_WORLD_TIME: { kor: '세계 내 시각', eng: 'In-world time' },
	DOCUMENT_CLAIM_RECORD: { kor: '기록', eng: 'Record' },
	DOCUMENT_CLAIM_STATEMENT: { kor: '발언', eng: 'Statement' },
	DOCUMENT_CLAIM_REPORT: { kor: '보고', eng: 'Report' },
	DOCUMENT_CLAIM_RUMOR: { kor: '소문', eng: 'Rumor' },
	DOCUMENT_CLAIM_OPINION: { kor: '의견·반응', eng: 'Opinion / reaction' },
	DOCUMENT_CLAIM_PROPAGANDA: { kor: '선전', eng: 'Propaganda' },
	DOCUMENT_CLAIM_UNKNOWN: { kor: '미분류', eng: 'Unknown' },
	DOCUMENT_CONTENT: { kor: '문서 내용', eng: 'Document content' },
	DOCUMENT_STATUS_DRAFT: { kor: '초안', eng: 'Draft' },
	DOCUMENT_STATUS_APPROVED: { kor: '승인됨', eng: 'Approved' },
	DOCUMENT_STATUS_ARCHIVED: { kor: '보관됨', eng: 'Archived' },
	DELETE: { kor: '삭제', eng: 'Delete' },
	APPROVE: { kor: '승인', eng: 'Approve' },
	ARCHIVE: { kor: '보관', eng: 'Archive' },
	CONFIRM_APPROVE_DOCUMENT: {
		kor: '이 문서를 승인하면 더 이상 직접 편집할 수 없습니다. 승인할까요?',
		eng: 'Approving this document prevents further direct editing. Approve it?',
	},
	CONFIRM_DELETE_DOCUMENT: { kor: '이 초안을 삭제할까요?', eng: 'Delete this draft?' },
	VIEW_CHARACTER_IMAGE: { kor: '캐릭터 이미지 보기', eng: 'View character image' },
	AVATAR_MISSING: { kor: '아바타 없음', eng: 'Avatar missing' },
	SAVE_CHANGES: { kor: '변경 사항 저장', eng: 'Save changes' },
	PROFILE_CARD_TABS: { kor: '프로필 카드 탭', eng: 'Profile card tabs' },
	ERROR_OCCURRED: { kor: '오류가 발생했습니다.', eng: 'An error occurred.' },
	AI_MODELS: { kor: 'AI 모델', eng: 'AI Models' },
	NONE: { kor: '없음', eng: 'None' },
	PROVIDER: { kor: '제공자', eng: 'Provider' },
	SHOW_API_KEY: { kor: 'API 키 표시', eng: 'Show API key' },
	CANCEL_EDIT: { kor: '편집 취소', eng: 'Cancel edit' },
	PREVIOUS_RESPONSE: { kor: '이전 응답', eng: 'Previous response' },
	NEXT_RESPONSE: { kor: '다음 응답', eng: 'Next response' },
	EDIT_THIS_TURN: { kor: '이 턴 편집', eng: 'Edit this turn' },
	REGENERATE_RESPONSE: { kor: '응답 다시 생성', eng: 'Regenerate response' },
	AI_MODEL: { kor: 'AI 모델', eng: 'AI Model' },
	ADULT_SESSION: { kor: '성인 세션', eng: 'Adult session' },
	GENERAL_SESSION: { kor: '일반 세션', eng: 'General session' },
	SESSIONS_WITH_CHARACTER: { kor: '지난 이야기', eng: 'Past Sessions' },
	CREATE_NEW_PROFILE: { kor: '새 프로필 만들기', eng: 'Create a New Profile' },
	CREATE_PROFILE: { kor: '프로필 생성', eng: 'Create Profile' },
	EDIT_PROFILE: { kor: '프로필 수정', eng: 'Update Profile' },
	CHOOSE_EXISTING_PROFILE: { kor: '기존 프로필', eng: 'Existing Profiles' },
	START_NEW_SESSION: { kor: '새로운 대화 시작하기', eng: 'Start a New Conversation' },
	ENTER_DATE: { kor: '가입일', eng: 'Entered Date' },
	CREATE_DATE: { kor: '생성일', eng: 'Created Date' },
	UPDATE_DATE: { kor: '수정일', eng: 'Updated Date' },
	LAST: { kor: '마지막', eng: 'Last' },
	GENDER: { kor: '성별', eng: 'Gender' },
	MALE: { kor: '남성', eng: 'Male' },
	FEMALE: { kor: '여성', eng: 'Female' },
	OTHER: { kor: '기타', eng: 'Other' },
	NOCOMMENT: { kor: '비공개', eng: 'No Comment' },
	EMAIL: { kor: '이메일', eng: 'Email' },
	ERROR: { kor: '에러', eng: 'Error' },
	STATISTICS: { kor: '활동 통계', eng: 'Statistics' },
	USER_INFO: { kor: '내 정보', eng: 'My Info' },
	EDIT_USER_INFO: { kor: '내 정보 수정', eng: 'Edit My Info' },
	CHARACTERS: { kor: '캐릭터', eng: 'Characters' },
	MY_CHARACTERS: { kor: '내 캐릭터', eng: 'My Characters' },
	MY_SESSIONS: { kor: '내 대화', eng: 'My Sessions' },
	LOGOUT: { kor: '로그아웃', eng: 'Logout' },
	EDIT: { kor: '수정', eng: 'Edit' },
	SEND: { kor: '보내기', eng: 'Send' },
	TITLE: { kor: '한줄 소개', eng: 'Tagline' },
	STORY: { kor: '스토리', eng: 'Story' },
	CANCEL: { kor: '취소', eng: 'Cancel' },
	CREATING: { kor: '생성중...', eng: 'Creating...' },
	UPDATING: { kor: '수정중...', eng: 'Updating...' },
	CREATE: { kor: '생성', eng: 'Create' },
	UPDATE: { kor: '수정', eng: 'Update' },
	SAVE: { kor: '저장', eng: 'Save' },
	SAVE_ANYWAY: { kor: '강제 저장', eng: 'Save Anyway' },
	USER_NOTE: { kor: '유저 노트', eng: 'User Note' },
	MORE: { kor: '더보기', eng: 'More' },
	API_KEYS: { kor: 'API 키', eng: 'API Keys' },
	API_KEYS_DESCRIPTION: {
		kor: 'API 키는 암호화되어 안전하게 저장됩니다. 대화 기능을 사용하려면 본인의 AI 서비스 API 키를 입력해야 합니다.',
		eng: 'Your API keys are encrypted and stored securely. You must enter your own AI service API keys to use chat features.',
	},
	MODIFIED: { kor: '수정됨', eng: 'Modified' },
	VALIDATING: { kor: '검증 중...', eng: 'Validating...' },
	API_KEY_VALIDATION_RESULTS: { kor: 'API 키 검증 결과', eng: 'API Key Validation Results' },
	API_KEYS_VALIDATION_WARNING: {
		kor: '일부 API 키에 문제가 있습니다. 저장은 가능하지만 채팅에서 작동하지 않을 수 있습니다:',
		eng: 'Some API keys have issues. You can still save them, but they might not work for chat:',
	},
	API_KEY_IS_VALID: { kor: 'API 키가 유효합니다', eng: 'API key is valid' },
	API_KEY_IS_INVALID: { kor: 'API 키가 유효하지 않습니다', eng: 'API key is invalid' },
	VALIDATION_FAILED_NETWORK_ERROR: {
		kor: '검증 실패 - 네트워크 오류',
		eng: 'Validation failed - network error',
	},
	FAILED_TO_VALIDATE_API_KEYS: {
		kor: 'API 키 검증에 실패했습니다',
		eng: 'Failed to validate API keys',
	},
	SAVE_API_KEYS: { kor: 'API 키 저장', eng: 'Save API Keys' },
	SAVING: { kor: '저장 중...', eng: 'Saving...' },
	USER_TITLE: { kor: '나를 한마디로 소개해 봅시다.', eng: 'Sum me up in one line.' },
	LOADING_CHARACTERS: { kor: '캐릭터를 불러오는 중입니다...', eng: 'Loading characters...' },
	LOADING_SESSIONS: { kor: '지난 이야기를 불러오는 중입니다...', eng: 'Loading past sessions...' },
	LOADING_STORIES: {
		kor: '캐릭터 스토리를 불러오는 중입니다...',
		eng: 'Loading character stories...',
	},
	LOADING_STORY: { kor: '스토리를 불러오는 중입니다...', eng: 'Loading story...' },
	LOADING_USER: { kor: '내 정보를 불러오는 중입니다...', eng: 'Loading user info...' },
	CREATING_SESSION: { kor: '새 이야기를 시작하는 중입니다...', eng: 'Starting a new session...' },
	FAILED_LOAD_CHAT: {
		kor: '채팅을 불러오는 데 실패했습니다. 다시 시도해 주세요.',
		eng: 'Failed to load chat. Please try again.',
	},
	LOADING_CHAT: { kor: '채팅을 불러오는 중입니다...', eng: 'Loading chat...' },
	GEN_RESPONSE: { kor: '답변을 받아오는 중입니다...', eng: 'Generating response...' },
	STOP_GENERATION: { kor: '생성 중지', eng: 'Stop generation' },
	NEW_CHARACTER: { kor: '새 캐릭터', eng: 'New Character' },
	EDIT_CHARACTER: { kor: '캐릭터 수정', eng: 'Edit Character' },
	NEW_CHARACTER_TITLE: { kor: '새 캐릭터를 만들어봐요!', eng: `Let's make a new character!` },
	NO_IMAGES: { kor: '업로드된 이미지가 없습니다.', eng: 'No images uploaded.' },
	NO_SESSIONS: {
		kor: '지난 이야기가 없습니다. 새 이야기를 시작해봐요!',
		eng: `No sessions found. Let the story begins!`,
	},
	NO_PROFILES: { kor: '기존 프로필이 없습니다.', eng: `No profiles found.` },
	NO_HISTORIES: { kor: '캐릭터의 옛 이야기가 없습니다.', eng: `No character histories found.` },
	PORTRAIT: { kor: '초상화', eng: 'Portraits' },
	EMOTION: { kor: '감정', eng: 'Emotion' },
	BASIC_INFO: { kor: '기본 정보', eng: 'Basic Information' },
	NAME: { kor: '이름(영어)', eng: 'Name (English)' },
	SHOWNAME: { kor: '이름', eng: 'Display Name' },
	DESCRIPTION: { kor: '캐릭터 소개', eng: 'Character Introduction' },
	WORLD_INTRODUCTION: { kor: '세계관 소개', eng: 'World Introduction' },
	CONTACT: { kor: '연락처', eng: 'Contact' },
	INSTRUCTION: { kor: '캐릭터 설정 및 연기 지침', eng: 'Persona Instructions' },
	SELECT_IMAGE: { kor: '이미지 선택', eng: 'Select Image' },
	CHARACTER_DETAIL: { kor: '상세 정보', eng: 'Details' },
	SESSION_TITLE: { kor: '대화방 이름', eng: 'Session Title' },
	TITLE_GUIDANCE: {
		kor: '한줄 소개는 다른 사람들에게 보이는 정보이며, AI 답변에 사용되지 않습니다.',
		eng: 'This tagline is shown to other users and does not affect AI responses.',
	},
	FIRST_MESSAGE: { kor: '첫 메시지', eng: 'First Message' },
	SHOW_NAME_REQUIRED: { kor: '이름은 필수입니다.', eng: 'Display Name is required.' },
	NAME_REQUIRED: {
		kor: '캐릭터 이름(영어)은 필수입니다.',
		eng: 'Character Name (English, for ID) is required.',
	},
	GENDER_REQUIRED: { kor: '성별은 필수입니다.', eng: 'Gender is required.' },
	TITLE_REQUIRED: { kor: '한줄 소개는 필수입니다.', eng: 'Character Bio is required.' },
	DESCRIPTION_REQUIRED: {
		kor: '캐릭터 소개는 필수 항목입니다.',
		eng: 'Character description is required.',
	},
	WORLD_INTRODUCTION_REQUIRED: {
		kor: '세계관 소개는 필수 항목입니다.',
		eng: 'World introduction is required.',
	},
	INSTRUCTION_REQUIRED: {
		kor: '캐릭터 관련 정보는 필수 항목입니다.',
		eng: 'World & AI Instructions are required.',
	},
	WORLD_LORE_REQUIRED: {
		kor: '세계관 설정은 필수 항목입니다.',
		eng: 'World  Instructions are required.',
	},
	FIRST_MESSAGE_REQUIRED: { kor: '첫 메시지는 필수 항목입니다.', eng: 'First Message is required.' },
	SHOW_NAME_PLACEHOLDER: {
		kor: '캐릭터가 표시될 이름을 입력해 주세요.',
		eng: 'Enter the name to be displayed for the character.',
	},
	NAME_PLACEHOLDER: {
		kor: '캐릭터의 영어 이름을 한 단어로 작성해 주세요.',
		eng: "Enter a single English name for the character's ID.",
	},
	CONTACT_PLACEHOLDER: {
		kor: '캐릭터 작성자의 연락처 정보를 기재해 주세요.',
		eng: "Enter the contact information of the character's creator.",
	},
	TITLE_PLACEHOLDER: {
		kor: '다른 유저들에게 캐릭터를 소개해 주세요.',
		eng: 'Introduce your character to other users.',
	},
	DESCRIPTION_PLACEHOLDER: {
		kor: '캐릭터의 이름, 성별, 성격, 외모 등을 자세히 설명해주세요.',
		eng: "Describe the character's name, gender, personality, appearance, etc. in detail.",
	},
	WORLD_INTRODUCTION_PLACEHOLDER: {
		kor: '캐릭터를 선택하는 사용자가 알아야 할 세계와 상황을 소개해 주세요.',
		eng: 'Introduce the world and situation a user should know before selecting this character.',
	},
	INSTRUCTION_PLACEHOLDER: {
		kor: '선택 사항: 캐릭터의 말투, 행동 원칙과 응답 방식을 더 구체적으로 지정해 주세요.',
		eng: "Optional: Specify the character's speech, behavioral rules, and response style in more detail.",
	},
	FIRST_MESSAGE_PLACEHOLDER: {
		kor: '새 대화를 시작할 때 캐릭터가 보내는 첫 메시지입니다.',
		eng: "The character's first message when starting a new conversation.",
	},
	USER_NOTE_PLACEHOLDER: {
		kor: '캐릭터가 꼭 기억했으면 하는 내용을 적어 주세요.',
		eng: 'Write any details you want the character to remember.',
	},
	INSTRUCTION_HELPER: {
		kor: '선택 항목입니다. 비워두면 세계관 소개와 캐릭터 소개를 기본 설정으로 사용합니다.',
		eng: 'Optional. When empty, world and character introductions provide the baseline behavior context.',
	},
	DESCRIPTION_HELPER: {
		kor: '유저에게 공개되며 모든 AI 응답의 기본 캐릭터 정보로 사용됩니다.',
		eng: 'Visible to users and used as baseline character context for every AI response.',
	},
	WORLD_INTRODUCTION_HELPER: {
		kor: '캐릭터 범위의 공개 소개이며 모든 AI 응답의 기본 세계관 정보로 사용됩니다.',
		eng: 'A public, character-scoped introduction used as baseline world context for every AI response.',
	},
	WORLD_LORE_HELPER: {
		kor: '캐릭터의 세계관 설정입니다. 다른 캐릭터와 공유할 수 있습니다.',
		eng: 'Character world setting. Can be shared with other characters.',
	},
	FIRST_MESSAGE_HELPER: {
		kor: '채팅창에 표시되는 캐릭터의 첫 대화입니다.',
		eng: "This is the character's first line of dialogue shown in the chat window.",
	},
	ERROR_MAXLENGTH: { kor: '글자수 제한을 초과하였습니다.', eng: 'Too long texts.' },
	SAVE_SUCCESS: { kor: '저장에 성공하였습니다.', eng: 'Saving Success.' },

	// --- Emotion Translations ---
	NEUTRAL: { kor: '중립', eng: 'Neutral' },
	HAPPY: { kor: '행복', eng: 'Happy' },
	ANGRY: { kor: '화남', eng: 'Angry' },
	SAD: { kor: '슬픔', eng: 'Sad' },
	FEAR: { kor: '두려움', eng: 'Fear' },
	CURIOUS: { kor: '궁금함', eng: 'Curious' },
	AFFECTIONATE: { kor: '애정', eng: 'Affectionate' },
	EXCITED: { kor: '흥분', eng: 'Excited' },
	DISGUSTED: { kor: '역겨움', eng: 'Disgusted' },
	CONFIDENT: { kor: '자신감', eng: 'Confident' },
	ASHAMED: { kor: '부끄러움', eng: 'Ashamed' },
	AMAZED: { kor: '놀람', eng: 'Amazed' },
	BORED: { kor: '지루함', eng: 'Bored' },
	ROMANTIC: { kor: '낭만적인', eng: 'Romantic' },
	CONFLICTED: { kor: '혼란스러운', eng: 'Conflicted' },
};

export const alertToastConstants: LangRecord = {
	CREATE_NEW_PROFILE: {
		kor: '대화에 참여할 프로필을 생성해 주세요.',
		eng: 'Please create a profile to join the conversation.',
	},
	STATIC_SENDING_DISABLE: {
		kor: '샘플 사이트에서는 메시지를 보내실 수 없습니다.',
		eng: 'Sending messages is disabled on the sample site.',
	},
	STATIC_SESSION_DISABLE: {
		kor: '샘플 사이트에서는 새 대화를 시작하실 수 없습니다.',
		eng: 'Starting a new conversation is disabled on the sample site.',
	},
	CHARACTER_CREATED_SUCCESS: {
		kor: '캐릭터를 생성하였습니다.',
		eng: 'Character created successfully!',
	},
	CHARACTER_UPDATED_SUCCESS: {
		kor: '캐릭터를 수정하였습니다.',
		eng: 'Character updated successfully!',
	},
	INVALID_FILE_TYPE: {
		kor: '잘못된 파일 형식입니다. 이미지 파일을 업로드해주세요.',
		eng: 'Invalid file type. Please upload an image file.',
	},
	FILE_TOO_LARGE: {
		kor: '파일이 너무 큽니다. 5MB 미만의 이미지를 업로드해주세요.',
		eng: 'File is too large. Please upload an image smaller than 5MB.',
	},
	IMAGE_UPLOADED_FOR: {
		kor: '감정 이미지가 업로드되었습니다!',
		eng: 'Emotion image has been uploaded!',
	},
	FAILED_TO_CREATE_CHARACTER: {
		kor: '캐릭터 생성에 실패했습니다.',
		eng: 'Failed to create character.',
	},
	ERROR_CREATING_CHARACTER: {
		kor: '캐릭터 생성 중 오류가 발생했습니다. 다시 시도해주세요.',
		eng: 'An error occurred while creating the character. Please try again.',
	},
	API_KEYS_SAVED_SUCCESS: {
		kor: 'API 키가 성공적으로 저장되었습니다.',
		eng: 'API keys saved successfully!',
	},
	API_KEYS_SAVE_FAILED: { kor: 'API 키 저장에 실패했습니다.', eng: 'Failed to save API keys.' },
	LORE_SAVED_SUCCESS: {
		kor: '세계관 로어가 성공적으로 저장되었습니다.',
		eng: 'Lore saved successfully!',
	},
	HISTORY_SAVED_SUCCESS: {
		kor: '캐릭터 스토리가 성공적으로 저장되었습니다.',
		eng: 'Character History saved successfully!',
	},
};
